typeblaze/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^typingtests/', include('typingtest.urls', namespace='typingtest')),
	url(r'^admin/', include(admin.site.urls)),
]

typingtest/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<typing_test_id>[0-9]+)/vote/$', views.vote, name='vote')
]

typingtest/models.py
from django.db import models

class Feature(models.Model):
	name = models.CharField(max_length=140, unique=True)

	def __str__(self):
		return '%s' % self.name

class TypingTest(models.Model):
	name = models.CharField(max_length=140, unique=True)
	text = models.CharField(max_length=1024)
	upvotes = models.IntegerField(default=0)
	downvotes = models.IntegerField(default=0)
	features = models.ForeignKey(Feature)
	times_taken = models.IntegerField(default=0)

	def __str__(self):
		return '%s' % self.name

typingtest/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse
from django.template import RequestContext, loader
from django.views import generic

from .models import TypingTest

class IndexView(generic.ListView):
	template_name = 'typingtest/index.html'
	context_object_name = 'latest_typingtest_list'

	def get_queryset(self):
		return TypingTest.objects.order_by('-pk')[:5]

class DetailView(generic.DetailView):
	template_name = 'typingtest/detail.html'
	model = TypingTest

def vote(request, typing_test_id):
	try:
		typingtest = TypingTest.objects.get(pk=typing_test_id)
		vote_value = request.POST['vote']
		if vote_value == '1':
			typingtest.upvotes = typingtest.upvotes + 1
		elif vote_value == '2':
			typingtest.downvotes = typingtest.downvotes + 1
		else:
			return JsonResponse({'previousVote': False, 'error': 'Invalid vote value %s' % vote_value})

		typingtest.save()
	except TypingTest.DoesNotExist:
		return JsonResponse({'previousVote': False, 'error': 'Cannot vote on a question that does not exist.'})

	return JsonResponse({'previousVote': False, 'newUpvotes': typingtest.upvotes, 'newDownvotes': typingtest.downvotes})

typingtest/templates/typingtest/detail.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{{typingtest.name}}</title>

		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css" />
		<link rel="stylesheet" href="{% static 'typingtest/css/style.css' %}" />
	</head>
	<body>
		<!-- Display the nav bar -->
		{% include 'typingtest/nav.html' %}

		<!-- Display the test information -->
		<main>
			<div class="container">
				<div class="section">
					<div class="row">
						<div class="col s8 offset-s2">
							<h3> {{ typingtest.name }} </h3>
							<h5> Typing Test Information </h5>
							<p> Features: {{ typingtest.features }} </p>
							<p> Score: <span id="upvote-label">{{ typingtest.upvotes }}</span> upvotes - <span id="downvote-label">{{ typingtest.downvotes }}</span> downvotes </p>
							<input type="button" name="submit-form" id=1 value="Upvote" />
							<input type="button" name="submit-form" id=2 value="Downvote" />
							<p id="typing-test-text">{{ typingtest.text }}</p>

							<input type="text" id="typing-test-input" />
							<p id="wpm-label">0 wpm</p>
						</div>
					</div>
				</div>
			</div>
		</main>

		<!-- Display the footer -->
		{% include 'typingtest/foot.html' %}
		
		<!-- Loading javascript files -->
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
		<script type="text/javascript" src="{% static 'typingtest/js/cookie.js' %}"></script>
		<script type="text/javascript" src="{% static 'typingtest/js/typingtest.js' %}"></script>

		<!-- Build page specific javascript -->
		<script type="text/javascript">
			// Get our token for posting to the server
			var csrftoken = getCookie('csrftoken');

			// Check for up or down votes
			$('input[name=submit-form]').click(function(event){
				var post = $.post("{% url 'typingtest:vote' typingtest.id %}", {'vote': event.target.id, "csrfmiddlewaretoken": csrftoken}, function(data){
					if(data['error']) {
						
					} else {
						$('#upvote-label').html(data['newUpvotes']);
						$('#downvote-label').html(data['newDownvotes']);
					}
				});
			});

			// Grabbing necessary DOM elements
			var textLabel = $('#typing-test-text');
			var inputField = $('#typing-test-input');
			var speedLabel = $('#wpm-label');

			// Initializing our typing test
			var typingTest = new TypingTest(textLabel, inputField, speedLabel);
			typingTest.onTestCompletion(function(time, wpm) {
				// Handle the completion of the test
				console.log('Test Finished');
			});
		</script>
	</body>
</html>

typingtest/templates/typingtest/foot.html
<footer class="page-footer orange">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">TypeBlaze</h5>
				<p class="grey-text text-lighten-4">Created by a computer science student who once upon a time typed slowly.</p>
			</div>
			<div class="col l3 s12">
				<h5 class="white-text">Settings</h5>
				<ul>
					<li><a class="white-text" href="#!">Link 1</a></li>
					<li><a class="white-text" href="#!">Link 2</a></li>
					<li><a class="white-text" href="#!">Link 3</a></li>
					<li><a class="white-text" href="#!">Link 4</a></li>
				</ul>
			</div>

			<div class="col l3 s12">
				<h5 class="white-text">Connect</h5>
				<ul>
					<li><a class="white-text" href="#!">Link 1</a></li>
					<li><a class="white-text" href="#!">Link 2</a></li>
					<li><a class="white-text" href="#!">Link 3</a></li>
					<li><a class="white-text" href="#!">Link 4</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
		Made by Casey Richardson
		</div>
	</div>
</footer>

typingtest/templates/typingtest/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'typingtest/style.css' %}" />
{% if latest_typingtest_list %}
	<ul>
	{% for typingtest in latest_typingtest_list %}
		<li><a href="{% url 'typingtest:detail' typingtest.id %}">{{ typingtest.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> No challenges are available </p>
{% endif %}

typingtest/templates/typingtest/nav.html
<nav class="red darken-1 z-depth-0" role="navigation">
	<div class="nav-wrapper container">
		<a id="logo-container" href="#" class="brand-logo thin">TypeBlaze</a>
		<ul class="right hide-on-med-and-down">
			<li><a href="#">Navbar Link</a></li>
		</ul>

		<ul id="nav-mobile" class="side-nav">
			<li><a href="#">Navbar Link</a></li>
		</ul>
		<a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
	</div>
</nav>